export enum DictQueryCriteria {
  VENDIBILITY_STATUS = "VENDIBILITY_STATUS", // 可卖状态
  SALES_AREA = "SALES_AREA", // 销售组织
  BARGAIN_PRIORITY = "BARGAIN_PRIORITY", // 议价优先级
  BIG_ORDER_REPORT = "BIG_ORDER_REPORT", // 是否允许大单报备
  MGMT_AREA = "MGMT_AREA", // 管理分区
  BARGAIN_SCENARIO = "BARGAIN_SCENARIO", // 议价场景
  CUSTOMER_AREA = "CUSTOMER_AREA", // 客户处
  PRODUCT_SCOPE = "PRODUCT_SCOPE", // 产品域
  SALES_METHOD = "SALES_METHOD", // 销售方式
  CUSTOMER_ATTRIBUTION = "CUSTOMER_ATTRIBUTION", // 客户归属
  CTO_TYPE = "CTO_TYPE", // ctoType 类型
}
